version: 0.0
Resources:
  - TargetService:
      Type: AWS::EC2::Instance
      Properties:
        UserData:
          Fn::Base64: |
            #!/bin/bash
            docker run -d -p 80:80 ${IMAGE_URI}
