version: 0.0
Resources:
  - TargetService:
      Type: AWS::EC2::Instance
      Properties:
        ImageId: latest  # 实际由 CloudFormation 动态替换
        UserData:
          Fn::Base64: |
            #!/bin/bash
            # 安装 Docker 并运行指定镜像
            yum update -y
            amazon-linux-extras install docker -y
            service docker start
            usermod -a -G docker ec2-user
            docker run -d -p 80:80 ${ECR_IMAGE_URI}
